[theme]
primaryColor = "#FF4B4B"        # Cor primária (botões, sliders)
backgroundColor = "#0E1117"     # Fundo da página (preto)
secondaryBackgroundColor = "#262730"  # Fundo de cards/sidebar (cinza escuro)
textColor = "#FAFAFA"           # Cor do texto (branco)
font = "sans serif"             # Fonte

base = "dark"  # Tema base: "dark" ou "light"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"     # Fundo branco
secondaryBackgroundColor = "#F0F2F6"  # Cinza claro
textColor = "#262730"           # Texto escuro
font = "sans serif"

base = "light"
